### ISSUE TITLE
Missing some files at compile time. src-tauri/icons/32x32.png: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by koakh** [rust-awesome-app/template-app-base#2]
Hello

first, congratulations for the awesome video about this surreal technologies, 
what a tech stack, the best combination ever :)
one of the best tauri | surrealdb videos I ever see

so well explained and clear, a bit complex to for new comers

I try to compile the project and have bellow error

```shell
   Compiling ts-rs v6.2.0
   Compiling webkit2gtk v0.18.1
error: proc macro panicked
  --> src/main.rs:47:8
   |
47 |         .run(tauri::generate_context!())
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: failed to read icon /mnt/storage/Development/SurrealDb/@ShowCase/RustTauriAwesomeAppWithSurrealDB/src-tauri/icons/32x32.png: No such file or directory (os error 2)

error: could not compile `app` due to previous error
FAIL - Fail to execute cargo cause: 
``` 

I note you have a file in your video that in not here `Awesome.toml`
can you upload all files like you have in the video that way we can follow it

thanks @jeremychone 

once more great job with this embedded surrealdb tauri project :)

Koakh

**Comment by jeremychone** [comment]
First, thanks for the kind words and trying it out. 

- It seems you are not using `awesome-app dev` command. You probably should run that.

- `Awesome.toml` used only by `awesome-app dev`, and will get generated if not present.  This allows keeping it as in sync as possible with the version of the `awesome-app` as possible. 

Now to build it manually, you can repeat what the `awesome-app dev` does by running the following commands (but will take some effort to have the concurrency and all, this is what `awesome-app dev` does)

```toml
[[dev.runners]]
name = "npm_install"
cmd = "npm"
args = ["install"]

[[dev.runners]]
name = "tauri_icons"
when.no_file_at = "src-tauri/icons/32x32.png"
cmd = "npm"
args = ["run", "tauri", "icon", "src-tauri/icons/app-icon.png"]

[[dev.runners]]
name = "cargo_build"
working_dir = "src-tauri/"
cmd = "cargo"
args = ["build"]

[[dev.runners]]
name = "pcss"
cmd = "npm"
args = ["run", "pcss", "--", "-w"]
concurrent = true 
# if this process exit, end the dev session
end_all_on_exit = true

[[dev.runners]]
name = "rollup"
cmd = "npm"
args = ["run", "rollup", "--", "-w"]
concurrent = true
end_all_on_exit = true

[[dev.runners]]
name = "localhost"
cmd = "npm"
args = ["run", "localhost"]
concurrent = true
end_all_on_exit = true

[[dev.runners]]
name = "tauri_dev"
wait_before = 2000 # wait in ms, before getting called
cmd = "npm"
args = ["run", "tauri", "dev"]
concurrent = true
end_all_on_exit = true

```
